# Generated by Django 4.1 on 2023-04-14 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('React_Blog', '0002_alter_post_options_alter_comments_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replies',
            name='main_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='React_Blog.comments'),
        ),
    ]
